version: '3.4'

services:
  dinheiro:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=dinheirodb;Username=postgres;Password=postgres;
    ports:
      - "8081:8080"
    depends_on:
    
      - db
  db:
   image: postgres:latest
   environment:
      POSTGRES_DB: dinheirodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
   ports:
      - "5432:5432"
