version: '3.4'

services:
  game:
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GameDB;User Id=unitins;Password=supersenha12345;
