version: '3.4'

services:
  game:
    image: ${DOCKER_REGISTRY-}game
    build:
      context: .
      dockerfile: Game/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=pclenda\SQLEXPRESS;Database=GameDB;User=unitins;Password=ComplexPassword123!;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=True

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "ComplexPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
