version: '3.4'

services:
  game:
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=pclenda\SQLEXPRESS;Database=GameDB;User=unitins;Password=ComplexPassword123!;MultipleActiveResultSets=true;Encrypt=True;TrustServerCertificate=True
