version: '3.4'

services:
  game:
    image: ${DOCKER_REGISTRY-}game
    build:
      context: .
      dockerfile: Game/Dockerfile
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: "supersenha12345"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
