// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Dinheiro.Models;

public partial class DinheirodbContext : DbContext
{
    public DinheirodbContext(DbContextOptions<DinheirodbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Moeda> Moeda { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasPostgresExtension("uuid-ossp");

        modelBuilder.Entity<Moeda>(entity =>
        {
            entity.ToTable("moeda");

            entity.Property(e => e.Id)
                .HasColumnName("id")
                .UseIdentityAlwaysColumn();

            entity.Property(e => e.Nome)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nome")
                .IsUnicode(false);

            entity.Property(e => e.Pais)
                .HasMaxLength(100)
                .HasColumnName("pais")
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}