// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Dinheiro.Models;

[Table("moeda")]
public partial class Moeda
{
    [Column("id")]
    [Key]
    public long? Id { get; set; }

    [Column("nome")]
    [StringLength(50)]
    [Unicode(false)]
    public string Nome { get; set; }

    [Column("pais")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pais { get; set; }
}